### PR TITLE
adding interfaces for type hints

### PR DESCRIPTION
**Pull request by akmazian**
hiii Scott,

Before I start I just wanna say thank you so much for creating this package :) It has truly been super helpful since our lab only has one set of FACSdiva (yikes). Anyways, here's a quick PR that added .pyi files for type hints 💡

If you don't mind taking a look at those and lemme know if anything feels off!

Best,
AZ Zhang
Ünal-Brar Labs
UC Berkeley

### CODE REVIEW

**Comment by whitews** [comment]
Hi @akmazian 

Thanks for putting this together. I'm familiar with interfaces in Java, but haven't used them in Python. Doing a cursory search about pyi files, they seem more similar to C header files. Can you elaborate on the benefits / uses of them? I'm not 100% sold on the idea, since at first glance it appears they would, at a minimum, add a maintenance burden if the API changes.

I have a few more thoughts, but wanted to hear more on the benefits before putting too much work into this.

Again, thanks for taking the time to do this,
Scott

**Comment by akmazian** [comment]
That makes sense! I haven't really thought about all that 🤔 I usually just type the files in place. The only benefit of .pyi files I can think of is type hints in IDEs like VSCode and PyCharm. I find them helpful as an end-user for the autocompletion and type "safety" those offer.

Totally cool if you think it adds too much maintenance burden, I'll just keep the fork open for myself :)

**Comment by akmazian** [comment]
yessir 🫡 it's literally just replacing the function declarations with the added type hints. I didn't do that because often people are more hesitant for whatever reasons. But if you are okay with that I can definitely combine the files!

**Comment by whitews** [comment]
Closing this for now. I'm still interested in experimenting with adding type hints. However, for any future PRs related to this, please submit an issue first so we can discuss, as I realize this is a significant effort.

**Comment by akmazian** [comment]
oh don't worry there won't be future PRs

**Pull request closed without merging**
